import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { ArrowRight, TrendingUp, DollarSign, Shield, Users, Zap } from "lucide-react";

export const metadata = { title: "Partners" };

export default function PartnersPage() {
  const ibBenefits = [
    "Competitive Commission Structure",
    "Marketing Support & Materials",
    "Dedicated Partner Manager",
    "Real-time Reporting Dashboard",
    "Co-branded Opportunities",
    "Training & Educational Resources",
  ];

  const faqs = [
    {
      q: "What are the minimum requirements to become an IB?",
      a: "You must have a minimum of 5 referred clients with combined volume of at least 50 lots per month. We also require a professional track record and compliance with our terms.",
    },
    {
      q: "How are commissions calculated?",
      a: "Commissions are based on trading volume generated by your referred clients. Our competitive tiered structure rewards higher volumes. Detailed commission tables are provided upon partnership agreement.",
    },
    {
      q: "What marketing support do you provide?",
      a: "We provide marketing materials, co-branded content, webinar support, and guidance on client acquisition strategies. Your dedicated manager will work with you to create a customized plan.",
    },
    {
      q: "Is there a contract term?",
      a: "Yes, partnerships typically have a 12-month initial term with automatic renewal. We're flexible and can discuss custom arrangements based on your situation.",
    },
  ];

  return (
    <main className="min-h-screen bg-gray-50">
      {/* Hero Section */}
      <section className="relative bg-gradient-to-r from-teal-500 via-emerald-600 to-teal-600 text-white py-16 px-4">
        <div className="max-w-7xl mx-auto">
          <h1 className="text-4xl md:text-5xl font-bold mb-4">
            Partnership Opportunities at BCR
          </h1>
          <p className="text-xl text-teal-50 max-w-2xl">
            Grow your business with BCR. Partner with us as an Introducing Broker and unlock lucrative opportunities.
          </p>
        </div>
      </section>

      <section className="max-w-7xl mx-auto px-4 py-16">
        {/* Partnership Programs */}
        <div className="mb-16">
          <h2 className="text-3xl font-bold text-gray-900 mb-12">Partnership Programs</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {/* Introducing Broker Program */}
            <Card className="p-8 border-gray-200">
              <div className="flex items-center justify-center w-12 h-12 rounded-lg bg-teal-100 mb-4">
                <Users className="w-6 h-6 text-teal-600" />
              </div>
              <h3 className="text-2xl font-bold text-gray-900 mb-4">Introducing Broker (IB)</h3>
              <p className="text-gray-600 mb-6">
                Earn competitive commissions by referring clients to BCR. Build a passive income stream while providing clients with access to premium trading services.
              </p>

              <h4 className="font-semibold text-gray-900 mb-3">Program Benefits:</h4>
              <ul className="space-y-2 mb-8">
                {ibBenefits.map((benefit, idx) => (
                  <li key={idx} className="text-sm text-gray-600 flex items-start">
                    <svg className="w-4 h-4 text-teal-600 mr-2 mt-0.5 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" /></svg>
                    <span>{benefit}</span>
                  </li>
                ))}
              </ul>

              <Button className="w-full bg-teal-600 hover:bg-teal-700 text-white">
                Learn More About IB Program
                <ArrowRight className="ml-2 w-4 h-4" />
              </Button>
            </Card>
          </div>
        </div>

        {/* Why Partner with BCR */}
        <div className="mb-16">
          <h2 className="text-3xl font-bold text-gray-900 mb-12">Why Partner with BCR?</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <Card className="p-6 border-gray-200 hover:shadow-lg transition">
              <div className="flex items-center justify-center w-12 h-12 rounded-lg bg-emerald-100 mb-4">
                <TrendingUp className="w-6 h-6 text-emerald-600" />
              </div>
              <h3 className="text-lg font-semibold text-gray-900 mb-2">Proven Track Record</h3>
              <p className="text-gray-600 text-sm">
                Over 18 years serving traders worldwide with consistent growth and reliability.
              </p>
            </Card>

            <Card className="p-6 border-gray-200 hover:shadow-lg transition">
              <div className="flex items-center justify-center w-12 h-12 rounded-lg bg-emerald-100 mb-4">
                <DollarSign className="w-6 h-6 text-emerald-600" />
              </div>
              <h3 className="text-lg font-semibold text-gray-900 mb-2">Competitive Pricing</h3>
              <p className="text-gray-600 text-sm">
                Get the most competitive spreads and commissions in the industry.
              </p>
            </Card>

            <Card className="p-6 border-gray-200 hover:shadow-lg transition">
              <div className="flex items-center justify-center w-12 h-12 rounded-lg bg-emerald-100 mb-4">
                <Shield className="w-6 h-6 text-emerald-600" />
              </div>
              <h3 className="text-lg font-semibold text-gray-900 mb-2">Regulatory Excellence</h3>
              <p className="text-gray-600 text-sm">
                Regulated by 3 top-tier authorities with strict compliance standards.
              </p>
            </Card>

            <Card className="p-6 border-gray-200 hover:shadow-lg transition">
              <div className="flex items-center justify-center w-12 h-12 rounded-lg bg-emerald-100 mb-4">
                <Zap className="w-6 h-6 text-emerald-600" />
              </div>
              <h3 className="text-lg font-semibold text-gray-900 mb-2">Advanced Technology</h3>
              <p className="text-gray-600 text-sm">
                Leverage cutting-edge trading platforms and infrastructure.
              </p>
            </Card>

            <Card className="p-6 border-gray-200 hover:shadow-lg transition">
              <div className="flex items-center justify-center w-12 h-12 rounded-lg bg-emerald-100 mb-4">
                <Users className="w-6 h-6 text-emerald-600" />
              </div>
              <h3 className="text-lg font-semibold text-gray-900 mb-2">Expert Support</h3>
              <p className="text-gray-600 text-sm">
                Dedicated partnership managers available 24/5 to support your success.
              </p>
            </Card>

            <Card className="p-6 border-gray-200 hover:shadow-lg transition">
              <div className="flex items-center justify-center w-12 h-12 rounded-lg bg-emerald-100 mb-4">
                <TrendingUp className="w-6 h-6 text-emerald-600" />
              </div>
              <h3 className="text-lg font-semibold text-gray-900 mb-2">Growth Potential</h3>
              <p className="text-gray-600 text-sm">
                Scale your business with our global client base and expanding opportunities.
              </p>
            </Card>
          </div>
        </div>

        {/* FAQ */}
        <div className="mb-16">
          <h2 className="text-3xl font-bold text-gray-900 mb-8">Frequently Asked Questions</h2>
          <div className="space-y-4 max-w-3xl">
            {faqs.map((faq, idx) => (
              <Card key={idx} className="p-6 border-gray-200">
                <h3 className="font-semibold text-gray-900 mb-2">{faq.q}</h3>
                <p className="text-gray-600">{faq.a}</p>
              </Card>
            ))}
          </div>
        </div>

        {/* CTA Section */}
        <Card className="p-12 bg-gradient-to-r from-teal-600 to-emerald-600 text-white text-center border-0">
          <h2 className="text-3xl font-bold mb-4">Ready to Become a BCR Partner?</h2>
          <p className="text-lg text-teal-100 mb-8 max-w-2xl mx-auto">
            Contact our partnerships team today to discuss how we can grow together.
          </p>
          <Button className="bg-white text-teal-600 hover:bg-gray-100 font-semibold">
            Get in Touch
            <ArrowRight className="ml-2 w-4 h-4" />
          </Button>
        </Card>
      </section>
    </main>
  );
}
